# Generated by Django 5.0.6 on 2024-06-20 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_product_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.register')),
            ],
        ),
    ]
