# Generated by Django 5.0.6 on 2024-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
