# Generated by Django 5.0.6 on 2024-06-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cart1')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart1',
            name='products',
            field=models.ManyToManyField(through='rentalapp.CartItem', to='rentalapp.product'),
        ),
    ]
