# Generated by Django 5.0.6 on 2024-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0009_alter_cartitem_quantity_rentalitem_renting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent_rate',
            field=models.FloatField(default=0),
        ),
    ]
