# Generated by Django 5.0.6 on 2024-07-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0010_product_rent_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='RentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_quantity', models.PositiveIntegerField(default=1)),
                ('rent_startdate', models.DateField()),
                ('rent_enddate', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.product')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.rent1')),
            ],
        ),
        migrations.AddField(
            model_name='rent1',
            name='products',
            field=models.ManyToManyField(through='rentalapp.RentItem', to='rentalapp.product'),
        ),
    ]
